name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install paramiko PyQt5

    - name: Build the executable
      run: |
        pyinstaller -F -w main.py

    - name: Archive the build output
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: dist/main.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: build-artifact
        path: dist

    - name: Create and Upload Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/main.exe
        tag_name: ${{ github.event.inputs.tag_name }}
        name: Release ${{ github.event.inputs.tag_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
